language: php
env:
  global:
    - DEFAULT_COMPOSER_FLAGS="--prefer-dist --no-interaction --no-progress --optimize-autoloader"
services:
  - memcached
  - mysql

php:
    - 5.5
    - 7.0
    
branches:
  only:
  - master
  - stable
before-install:
   - sh build.sh
install:
  - travis_retry composer self-update
script: php vendor/codeception/codeception/codecept run