language: php
env:
  global:
    - DEFAULT_COMPOSER_FLAGS="--prefer-dist --no-interaction --no-progress --optimize-autoloader"
services:
  - memcached
  - mysql

php:
    - 7.0
    
branches:
  only:
  - master
  - stable
deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  local_dir: dpl_cd_upload
  skip_cleanup: true
  on:
    repo: YB1010/sum-thing-wong-carshare
    all_branches: true
  bucket: socarpp1
  region: us-east-1
- provider: codedeploy
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: socarpp1
  key: latest.zip
  bundle_type: zip
  application: Carshare
  deployment_group: Carshare
  region: us-east-1
  on:
    all_branches: true
before-install:
   - sh build.sh
install:
  - travis_retry composer self-update
script: 
  - chmod +x pp1/vendor/bin/phpunit
  - zip -r latest *
  - mkdir -p dpl_cd_upload
  - mv latest.zip dpl_cd_upload/latest.zip