language: php
services:
  - memcached
  - mysql

php:
    - 5.5
    - 7.0
    
branches:
  only:
  - master
  - stable
install:
  - travis_retry composer self-update
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install $DEFAULT_COMPOSER_FLAGS
script: php vendor/codeception/codeception/codecept run