language: php

php:
    - 5.5
    - 7.0
    
branches:
  only:
  - master
  - stable
install:
    - composer self-update
    - composer install -d=/PP1
script: php vendor/codeception/codeception/codecept run